In [1]:
import numpy as np 
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
#Importamos los datos

X_train = pd.read_csv("./DatosAbandonoSinNanSub/X_train.csv", sep=',', decimal='.')
y_train = pd.read_csv("./DatosAbandonoSinNanSub/y_train.csv", sep=',', decimal='.')
#X_val = pd.read_csv("./DatosAbandonoSinNanSub/X_val.csv", sep=',', decimal='.')
#y_val = pd.read_csv("./DatosAbandonoSinNanSub/y_val.csv", sep=',', decimal='.')
X_test = pd.read_csv("./DatosAbandonoSinNanSub/X_test.csv", sep=',', decimal='.')
y_test = pd.read_csv("./DatosAbandonoSinNanSub/y_test.csv", sep=',', decimal='.')

In [4]:
from sklearn import preprocessing

#scaler = preprocessing.StandardScaler().fit(X_train)
scaler = preprocessing.Normalizer().fit(X_train)
X_train = scaler.transform(X_train)
#X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

In [5]:
# Grid search cross validation
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression


grid={"C":np.logspace( -4, 4, 50), "penalty":["l1","l2"]}# l1 lasso l2 ridge
logreg=LogisticRegression()
logreg_cv=GridSearchCV(logreg,grid,cv=10)
logreg_cv.fit(X_train,y_train)

print("tuned hpyerparameters :(best parameters) ",logreg_cv.best_params_)
print("accuracy :",logreg_cv.best_score_)

print("score",logreg_cv.score(X_test,y_test))

tuned hpyerparameters :(best parameters)  {'C': 159.98587196060572, 'penalty': 'l2'}
accuracy : 0.5691720814381633
score 0.6534637588197563


In [6]:
logreg2=LogisticRegression(C=0.0001,penalty="l2")
logreg2=LogisticRegression()
logreg2.fit(X_train,y_train)
print("score",logreg2.score(X_test,y_test))

score 0.645445798588839


In [8]:
from sklearn.metrics import classification_report, confusion_matrix

grid_predictions_lr = logreg2.predict(X_test)

# print classification report
print(classification_report(y_test, grid_predictions_lr))
print(confusion_matrix(y_test, grid_predictions_lr))

              precision    recall  f1-score   support

         0.0       0.77      0.76      0.76      4376
         1.0       0.00      0.00      0.00       533
         2.0       0.37      0.54      0.44      1327

    accuracy                           0.65      6236
   macro avg       0.38      0.43      0.40      6236
weighted avg       0.62      0.65      0.63      6236

[[3309    0 1067]
 [ 401    0  132]
 [ 611    0  716]]


In [7]:
from joblib import dump, load
dump(logreg_cv, 'logreg_cv_nor.joblib') 

['logreg_cv_nor.joblib']