[https://www.kaggle.com/code/viznrvn/optimal-parameters-for-svc-using-gridsearch/notebook](https://www.kaggle.com/code/viznrvn/optimal-parameters-for-svc-using-gridsearch/notebook)

[https://github.com/joanby/python-ml-course/tree/master/notebooks](https://github.com/joanby/python-ml-course/tree/master/notebooks)

In [1]:

import pandas as pd
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.svm import SVC

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
#Importamos los datos

X_train = pd.read_csv("./DatosAbandonoSinNan/X_train.csv", sep=',', decimal='.')
y_train = pd.read_csv("./DatosAbandonoSinNan/y_train.csv", sep=',', decimal='.')
X_val = pd.read_csv("./DatosAbandonoSinNan/X_val.csv", sep=',', decimal='.')
y_val = pd.read_csv("./DatosAbandonoSinNan/y_val.csv", sep=',', decimal='.')
X_test = pd.read_csv("./DatosAbandonoSinNan/X_test.csv", sep=',', decimal='.')
y_test = pd.read_csv("./DatosAbandonoSinNan/y_test.csv", sep=',', decimal='.')

In [4]:
# from sklearn import preprocessing

# scaler = preprocessing.StandardScaler().fit(X_train)
# scaler = preprocessing.Normalizer().fit(X_train)
# X_train = scaler.transform(X_train)
# X_val = scaler.transform(X_val)
# X_test = scaler.transform(X_test)

In [5]:
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf', 'linear']} 
  
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 1)
  
# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits


In [ ]:

# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

{'C': 0.1, 'gamma': 1, 'kernel': 'rbf'}
SVC(C=0.1, gamma=1)


In [ ]:
grid_predictions = grid.predict(X_test)

# print classification report
print(classification_report(y_test, grid_predictions))
print(confusion_matrix(y_test, grid_predictions))


              precision    recall  f1-score   support

           0       0.98      1.00      0.99      4652
           1       0.00      0.00      0.00       110
           2       0.00      0.00      0.00         6

    accuracy                           0.98      4768
   macro avg       0.33      0.33      0.33      4768
weighted avg       0.95      0.98      0.96      4768

[[4652    0    0]
 [ 110    0    0]
 [   6    0    0]]


In [ ]:
from joblib import dump, load
dump(grid, 'svc.joblib') 

['svc.joblib']

In [ ]:
#clf = load('svc.joblib') 