In [1]:
import numpy as np 
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
#Importamos los datos

X_train = pd.read_csv("./DatosAbandonoSinPondSinNanSub/X_train.csv", sep=',', decimal='.')
y_train = pd.read_csv("./DatosAbandonoSinPondSinNanSub/y_train.csv", sep=',', decimal='.')
#X_val = pd.read_csv("./DatosAbandonoSinPondSinNanSub/X_val.csv", sep=',', decimal='.')
#y_val = pd.read_csv("./DatosAbandonoSinPondSinNanSub/y_val.csv", sep=',', decimal='.')
X_test = pd.read_csv("./DatosAbandonoSinPondSinNanSub/X_test.csv", sep=',', decimal='.')
y_test = pd.read_csv("./DatosAbandonoSinPondSinNanSub/y_test.csv", sep=',', decimal='.')

In [4]:
y_train.value_counts()

DROPOUT_RISK
0.0             4985
2.0             4985
1.0             2183
dtype: int64

In [5]:
from sklearn import preprocessing

#scaler = preprocessing.StandardScaler().fit(X_train)
scaler = preprocessing.Normalizer().fit(X_train)
X_train = scaler.transform(X_train)
#X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

In [6]:
# Grid search cross validation
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression


grid={"C":np.logspace( -4, 4, 50), "penalty":["l1","l2"]}# l1 lasso l2 ridge
#logreg=LogisticRegression(class_weight="balanced") # El balanced es para balancear el dataset
logreg=LogisticRegression() # El balanced es para balancear el dataset
logreg_cv=GridSearchCV(logreg,grid,cv=10)
logreg_cv.fit(X_train,y_train)

print("tuned hpyerparameters :(best parameters) ",logreg_cv.best_params_)
print("accuracy :",logreg_cv.best_score_)

print("score",logreg_cv.score(X_test,y_test))

tuned hpyerparameters :(best parameters)  {'C': 109.85411419875572, 'penalty': 'l2'}
accuracy : 0.581601215616201
score 0.6351828094932649


In [7]:
#logreg2=LogisticRegression(C=16.109.85411419875572,penalty="l2", class_weight="balanced")
logreg2=LogisticRegression(C=109.85411419875572,penalty="l2")
logreg2=LogisticRegression()
logreg2.fit(X_train,y_train)
print("score",logreg2.score(X_test,y_test))

score 0.6294098781270044


In [8]:
from sklearn.metrics import classification_report, confusion_matrix

grid_predictions_lr = logreg2.predict(X_test)

# print classification report
print(classification_report(y_test, grid_predictions_lr))
print(confusion_matrix(y_test, grid_predictions_lr))

              precision    recall  f1-score   support

         0.0       0.75      0.75      0.75      4317
         1.0       0.00      0.00      0.00       579
         2.0       0.36      0.50      0.42      1340

    accuracy                           0.63      6236
   macro avg       0.37      0.42      0.39      6236
weighted avg       0.59      0.63      0.61      6236

[[3249    0 1068]
 [ 442    0  137]
 [ 664    0  676]]


In [9]:
from joblib import dump, load
dump(logreg_cv, 'logreg_cv_nor.joblib') 

['logreg_cv_nor.joblib']