In [7]:
import numpy as np 
import pandas as pd

In [8]:
import warnings
warnings.filterwarnings('ignore')

In [9]:
#Importamos los datos

X_train = pd.read_csv("./DatosAbandonoSinPondSinNanSub/X_train.csv", sep=',', decimal='.')
y_train = pd.read_csv("./DatosAbandonoSinPondSinNanSub/y_train.csv", sep=',', decimal='.')
#X_val = pd.read_csv("./DatosAbandonoSinPondSinNanSub/X_val.csv", sep=',', decimal='.')
#y_val = pd.read_csv("./DatosAbandonoSinPondSinNanSub/y_val.csv", sep=',', decimal='.')
X_test = pd.read_csv("./DatosAbandonoSinPondSinNanSub/X_test.csv", sep=',', decimal='.')
y_test = pd.read_csv("./DatosAbandonoSinPondSinNanSub/y_test.csv", sep=',', decimal='.')

In [10]:
# Grid search cross validation
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression


grid={"C":np.logspace( -4, 4, 50), "penalty":["l1","l2"]}# l1 lasso l2 ridge
logreg=LogisticRegression()
logreg_cv=GridSearchCV(logreg,grid,cv=10)
logreg_cv.fit(X_train,y_train)

print("tuned hpyerparameters :(best parameters) ",logreg_cv.best_params_)
print("accuracy :",logreg_cv.best_score_)

print("score",logreg_cv.score(X_test,y_test))

tuned hpyerparameters :(best parameters)  {'C': 0.0001, 'penalty': 'l2'}
accuracy : 0.4100221328784926
score 0.21488133418858243


In [11]:
#logreg2=LogisticRegression(C=0.0001,penalty="l2")
logreg2=LogisticRegression()
logreg2.fit(X_train,y_train)
print("score",logreg2.score(X_test,y_test))

score 0.21488133418858243


In [13]:
from sklearn.metrics import classification_report, confusion_matrix

grid_predictions_lr = logreg2.predict(X_test)

# print classification report
print(classification_report(y_test, grid_predictions_lr))
print(confusion_matrix(y_test, grid_predictions_lr))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00      4317
         1.0       0.00      0.00      0.00       579
         2.0       0.21      1.00      0.35      1340

    accuracy                           0.21      6236
   macro avg       0.07      0.33      0.12      6236
weighted avg       0.05      0.21      0.08      6236

[[   0    0 4317]
 [   0    0  579]
 [   0    0 1340]]


In [12]:
from joblib import dump, load
dump(logreg_cv, 'logreg_cv.joblib') 

['logreg_cv.joblib']